version: '3.7'

services:

  frontend:
    container_name: unitedbudget-frontend-dev
    image: unitedbudget-frontend-dev
    build:
      context: .
      target: development
    volumes:
      - './src:/app/src'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
